cronjob:
  metadata:
    name: qa-s3-file-creation
    namespace: qa
  spec:
    schedule: "*/5 * * * *"
    containers:
      registry: ""
      image: "python-s3-creation"
      tag: 0.0.1
      pullPolicy: IfNotPresent