cronjob:
  metadata:
    name: staging-s3-file-creation
    namespace: staging
  spec:
    schedule: "*/5 * * * *"
    containers:
      registry: "atilarmao"
      image: "s3-file-creation"
      tag: 0.0.2
      pullPolicy: IfNotPresent
    env:
      BUCKET_NAME: staging-atila-santos-platform-challange
      ACCESS_KEY: ""
      SECRET_KEY: ""